describe('Automation Practice Test',()=>{
    it('Navigate to url',()=>{
        cy.visit('http://automationpractice.com/index.php')
        cy.wait(1000)
    })
    it('Sign in',()=>{
        cy.get('.login').click()
        cy.wait(1000)
    })
    it('create account',()=>{
        cy.get('#email_create').click()
        cy.wait(5000)
        cy.get('#email_create').type('elimianmercy@gmail.com')
        cy.wait(5000)
        cy.get('#SubmitCreate > span').click()
        cy.wait(5000)
        cy.get('#id_gender2').click()
        cy.wait(5000)
        cy.get('#customer_firstname').type('Mercy')
        cy.wait(5000)
        cy.get('#customer_lastname').type('Elimian')
        cy.wait(5000)
        cy.get('#passwd').type('UnlimitedEmi')
        cy.wait(5000)
        cy.get('#days').select(5).should('have.value', '5')
        cy.wait(5000)
        cy.get('#months').select('April').should('have.value', '4')
        cy.wait(5000)
        cy.get('#years').select('2010').should('have.value', '2010')
        cy.wait(5000)
        // cy.get('#firstname').type('Mercy')
        // cy.get('#lastname').type('Elimian')
        cy.get('#company').type('Fintak Software Company')
        cy.get('#address1').type('641, Lexington Avenue, 10022, CorporateSuites')
        cy.get('#address2').type('144A Gbagada Road')
        cy.get('#city').type('New York')
        cy.get('#id_state').select('New York').should('have.value', '32')
        cy.wait(5000)
        cy.get('#postcode').type('00000')
        cy.get('#id_country').select('United States').should('have.value', '21')
        cy.wait(5000)
        cy.get('#other').type('ECommerce')
        cy.get('#phone').type('+2348127710276')
        cy.get('#phone_mobile').type('+2348123345365')
        cy.get('#alias').type('mercyAdd')
        cy.get('#submitAccount > span').click()

    })

    //to sign in and add to cart
    it('Login', ()=>{
        cy.get('.login').click()
        cy.get('#email').type('mercyelimian@gmail.com')
        cy.get('#passwd').type('Irenosen')
        cy.get('#SubmitLogin > span').click()
        cy.get('.logout').click()
        cy.wait(1000)
    })
    it('Login', ()=>{
        cy.get('.login').click()
        cy.get('#email').type('mercyelimian@gmail.com')
        cy.get('#passwd').type('Irenosen')
        cy.get('#SubmitLogin > span').click()
    }) 
    it('Filter', ()=>{
        cy.get('#search_query_top').type('blouse')
        cy.wait(2000)
        cy.get('#searchbox > .btn').click()
        cy.wait(2000)
        cy.get(':nth-child(2) > .products-block-image > .replace-2x').click()
        cy.wait(2000)
        cy.get('.breadcrumb > [href="http://automationpractice.com/index.php?id_category=4&controller=category"]').click()
        cy.wait(2000)
        cy.get(':nth-child(1) > .subcategory-image > .img > .replace-2x').click()
        cy.wait(2000)
    })       
    it('Add to cart',()=>{
        cy.get('.ajax_add_to_cart_button > span').click()
        cy.wait(5000)
        cy.get('.products-block-image > .replace-2x').click()
        cy.wait(2000)
        cy.get('.exclusive > span').click()
        cy.wait(2000)
        cy.get('.button-medium > span').click()
        //checkout
        cy.get('.cart_navigation > .button > span').click()
        cy.wait(2000)
    })
})
